services:

    omez_belinfonet.http_client: 
        class: GuzzleHttp\Client

    omez_belinfonet.website_client.abstract: 
        class: OmeZ\Bundle\BelinfonetBundle\WebsiteClient\WebsiteClient
        arguments: ["@omez_belinfonet.http_client", "", ""]
  
    omez_belinfonet.websize_client:
        class: OmeZ\Bundle\BelinfonetBundle\WebsiteClient\WebsiteClient
        synthetic: true
  
#    ome_z_belinfonet.example:
#        class: OmeZ\Bundle\BelinfonetBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
